ALTER TABLE "obra_documentos"
ADD COLUMN IF NOT EXISTS "ordem" INTEGER;

ALTER TABLE "obras"
ADD COLUMN IF NOT EXISTS "comprimento_maior" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "comprimento_menor" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "cor_stain" VARCHAR(50),
ADD COLUMN IF NOT EXISTS "is_l_shape" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "largura_maior" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "largura_menor" DECIMAL(10,2);

ALTER TABLE "orcamento"
ADD COLUMN IF NOT EXISTS "cor_stain" VARCHAR(50);

ALTER TABLE "pedido_itens"
ADD COLUMN IF NOT EXISTS "componente" VARCHAR(100);
