FROM node:20-bookworm-slim AS deps

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates openssl \
  && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

FROM deps AS builder

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

ARG DATABASE_URL
ARG AUTH_SECRET
ARG NEXTAUTH_URL
ARG NEXT_PUBLIC_ENDPOINT_GERAR_PDF
ARG NEXT_PUBLIC_ENDPOINT_LOGS_ORCAMENTO
ARG N8N_WEBHOOK_URL_ORDEM_SERVICO
ARG S3_ENDPOINT
ARG S3_BUCKET
ARG S3_REGION
ARG S3_ACCESS_KEY_ID
ARG S3_SECRET_ACCESS_KEY
ARG RESEND_API_KEY
ARG GIT_SHA

ENV DATABASE_URL=$DATABASE_URL
ENV AUTH_SECRET=$AUTH_SECRET
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXT_PUBLIC_ENDPOINT_GERAR_PDF=$NEXT_PUBLIC_ENDPOINT_GERAR_PDF
ENV NEXT_PUBLIC_ENDPOINT_LOGS_ORCAMENTO=$NEXT_PUBLIC_ENDPOINT_LOGS_ORCAMENTO
ENV N8N_WEBHOOK_URL_ORDEM_SERVICO=$N8N_WEBHOOK_URL_ORDEM_SERVICO
ENV S3_ENDPOINT=$S3_ENDPOINT
ENV S3_BUCKET=$S3_BUCKET
ENV S3_REGION=$S3_REGION
ENV S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
ENV S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV GIT_SHA=$GIT_SHA

COPY . .

RUN npx prisma generate && npm run build && npm prune --omit=dev

FROM node:20-bookworm-slim AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

ARG DATABASE_URL
ARG AUTH_SECRET
ARG NEXTAUTH_URL
ARG NEXT_PUBLIC_ENDPOINT_GERAR_PDF
ARG NEXT_PUBLIC_ENDPOINT_LOGS_ORCAMENTO
ARG N8N_WEBHOOK_URL_ORDEM_SERVICO
ARG S3_ENDPOINT
ARG S3_BUCKET
ARG S3_REGION
ARG S3_ACCESS_KEY_ID
ARG S3_SECRET_ACCESS_KEY
ARG RESEND_API_KEY
ARG GIT_SHA

ENV DATABASE_URL=$DATABASE_URL
ENV AUTH_SECRET=$AUTH_SECRET
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXT_PUBLIC_ENDPOINT_GERAR_PDF=$NEXT_PUBLIC_ENDPOINT_GERAR_PDF
ENV NEXT_PUBLIC_ENDPOINT_LOGS_ORCAMENTO=$NEXT_PUBLIC_ENDPOINT_LOGS_ORCAMENTO
ENV N8N_WEBHOOK_URL_ORDEM_SERVICO=$N8N_WEBHOOK_URL_ORDEM_SERVICO
ENV S3_ENDPOINT=$S3_ENDPOINT
ENV S3_BUCKET=$S3_BUCKET
ENV S3_REGION=$S3_REGION
ENV S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
ENV S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV GIT_SHA=$GIT_SHA

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates openssl \
  && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/public ./public
COPY --from=builder /app/prisma ./prisma

EXPOSE 3000

CMD ["npm", "start"]
